package world

// countryphoneCode - struct
type countryphoneCode struct {
	Name string
	Code string
	Next *countryphoneCode
}

// World - struct
type World struct {
	name string
	Head *countryphoneCode
}

// CreateWorld - create world
func CreateWorld(name string) *World {
	w := &World{
		name: name,
	}
	initializeCountries(w)
	return w
}

// addCountry - add country in given world
func (p *World) addCountry(name, code string) {
	countryPhone := &countryphoneCode{
		Name: name,
		Code: code,
	}
	if p.Head == nil {
		p.Head = countryPhone
	} else {
		currentCountry := p.Head
		for currentCountry.Next != nil {
			currentCountry = currentCountry.Next
		}
		currentCountry.Next = countryPhone
	}
	return
}

// initializeCountries - initialize all countries
func initializeCountries(w *World) {
	w.addCountry("Afghanistan", "+93")
	w.addCountry("Aland Islands", "+358")
	w.addCountry("Albania", "+355")
	w.addCountry("Algeria", "+213")
	w.addCountry("American Samoa", "+1")
	w.addCountry("Andorra", "+276")
	w.addCountry("Angola", "+244")
	w.addCountry("Anguilla", "+1")
	w.addCountry("Antigua and Barbuda", "+1")
	w.addCountry("Argentina", "+54")
	w.addCountry("Armenia", "+374")
	w.addCountry("Aruba", "+297")
	w.addCountry("Ascension Island", "+247")
	w.addCountry("Australia", "+61")
	w.addCountry("Australian Antarctic Territory", "+672")
	w.addCountry("Austria", "+43")
	w.addCountry("Azerbaijan", "+994")
	w.addCountry("Bahamas", "+1")
	w.addCountry("Bahrain", "+973")
	w.addCountry("Bangladesh", "+880")
	w.addCountry("Barbados", "+1")
	w.addCountry("Belarus", "+375")
	w.addCountry("Belgium", "+32")
	w.addCountry("Belize", "+501")
	w.addCountry("Benin", "+229")
	w.addCountry("Bermuda", "+1")
	w.addCountry("Bhutan", "+975")
	w.addCountry("Bolivia", "+591")
	w.addCountry("Bonaire", "+599")
	w.addCountry("Bosnia and Herzegovina", "+387")
	w.addCountry("Botswana", "+267")
	w.addCountry("Brazil", "+55")
	w.addCountry("British Indian Ocean Territory", "+246")
	w.addCountry("British Virgin Islands", "+1")
	w.addCountry("Brunei", "+673")
	w.addCountry("Bulgaria", "+359")
	w.addCountry("Burkina Faso", "+226")
	w.addCountry("Burma", "+95")
	w.addCountry("Burundi", "+257")
	w.addCountry("Cape Verde", "+238")
	w.addCountry("Cambodia", "+855")
	w.addCountry("Cameroon", "+237")
	w.addCountry("Canada", "+1")
	w.addCountry("Caribbean Netherlands", "+599")
	w.addCountry("Cayman Islands", "+1")
	w.addCountry("Central African Republic", "+236")
	w.addCountry("Chad", "+235")
	w.addCountry("Chatham Island, New Zealand", "+64")
	w.addCountry("Chile", "+56")
	w.addCountry("China", "+86")
	w.addCountry("Christmas Island", "+61")
	w.addCountry("Cocos (Keeling) Islands", "+61")
	w.addCountry("Colombia", "+57")
	w.addCountry("Comoros", "+269")
	w.addCountry("Congo", "+242")
	w.addCountry("Congo, Democratic Republic of the (Zaire)", "+243")
	w.addCountry("Cook Islands", "+682")
	w.addCountry("Costa Rica", "+506")
	w.addCountry("Ivory Coast", "+225")
	w.addCountry("Croatia", "+385")
	w.addCountry("Cuba", "+53")
	w.addCountry("Curaçao", "+599")
	w.addCountry("Cyprus", "+357")
	w.addCountry("Czech Republic", "+420")
	w.addCountry("Denmark", "+45")
	w.addCountry("Diego Garcia", "+246")
	w.addCountry("Djibouti", "+253")
	w.addCountry("Dominica", "+1")
	w.addCountry("Dominican Republic", "+1")
	w.addCountry("Easter Island", "+56")
	w.addCountry("Ecuador", "+593")
	w.addCountry("Egypt", "+20")
	w.addCountry("El Salvador", "+503")
	w.addCountry("Ellipso (Mobile Satellite service)", "+881")
	w.addCountry("EMSAT (Mobile Satellite service)", "+882")
	w.addCountry("Equatorial Guinea", "+240")
	w.addCountry("Eritrea", "+291")
	w.addCountry("Estonia", "+372")
	w.addCountry("eSwatini", "+268")
	w.addCountry("Ethiopia", "+251")
	w.addCountry("Falkland Islands", "+500")
	w.addCountry("Faroe Islands", "+298")
	w.addCountry("Fiji", "+679")
	w.addCountry("Finland", "+358")
	w.addCountry("France", "+33")
	w.addCountry("French Antilles", "+596")
	w.addCountry("French Guiana", "+594")
	w.addCountry("French Polynesia", "+689")
	w.addCountry("Gabon", "+241")
	w.addCountry("Gambia", "+220")
	w.addCountry("Georgia", "+995")
	w.addCountry("Germany", "+49")
	w.addCountry("Ghana", "+233")
	w.addCountry("Gibraltar", "+350")
	w.addCountry("Global Mobile Satellite System (GMSS)", "+881")
	w.addCountry("Greece", "+30")
	w.addCountry("Greenland", "+299")
	w.addCountry("Grenada", "+1")
	w.addCountry("Guadeloupe", "+590")
	w.addCountry("Guam", "+1")
	w.addCountry("Guatemala", "+502")
	w.addCountry("Guernsey", "+44")
	w.addCountry("Guinea", "+224")
	w.addCountry("Guinea-Bissau", "+245")
	w.addCountry("Guyana", "+592")
	w.addCountry("Haiti", "+509")
	w.addCountry("Honduras", "+504")
	w.addCountry("Hong Kong", "+852")
	w.addCountry("Hungary", "+36")
	w.addCountry("Iceland", "+354")
	w.addCountry("India", "+91")
	w.addCountry("Indonesia", "+62")
	w.addCountry("Inmarsat SNAC", "+870")
	w.addCountry("International Freephone Service (UIFN)", "+800")
	w.addCountry("International Networks", "+882")
	w.addCountry("International Networks", "+883")
	w.addCountry("International Premium Rate Service", "+979")
	w.addCountry("International Shared Cost Service (ISCS)", "+808")
	w.addCountry("Iran", "+98")
	w.addCountry("Iraq", "+964")
	w.addCountry("Ireland", "+353")
	w.addCountry("Iridium (Mobile Satellite service)", "+881")
	w.addCountry("Isle of Man", "+44")
	w.addCountry("Israel", "+972")
	w.addCountry("Italy", "+39")
	w.addCountry("Jamaica", "+1")
	w.addCountry("Jan Mayen", "+47")
	w.addCountry("Japan", "+81")
	w.addCountry("Jersey", "+44")
	w.addCountry("Jordan", "+962")
	w.addCountry("Kazakhstan", "+7")
	w.addCountry("Kenya", "+254")
	w.addCountry("Kiribati", "+686")
	w.addCountry("Korea, North", "+850")
	w.addCountry("Korea, South", "+82")
	w.addCountry("Kosovo", "+383")
	w.addCountry("Kuwait", "+965")
	w.addCountry("Kyrgyzstan", "+996")
	w.addCountry("Laos", "+856")
	w.addCountry("Latvia", "+371")
	w.addCountry("Lebanon", "+961")
	w.addCountry("Lesotho", "+266")
	w.addCountry("Liberia", "+231")
	w.addCountry("Libya", "+218")
	w.addCountry("Liechtenstein", "+423")
	w.addCountry("Lithuania", "+370")
	w.addCountry("Luxembourg", "+352")
	w.addCountry("Macau", "+853")
	w.addCountry("Madagascar", "+261")
	w.addCountry("Malawi", "+265")
	w.addCountry("Malaysia", "+60")
	w.addCountry("Maldives", "+960")
	w.addCountry("Mali", "+223")
	w.addCountry("Malta", "+356")
	w.addCountry("Marshall Islands", "+692")
	w.addCountry("Martinique", "+596")
	w.addCountry("Mauritania", "+222")
	w.addCountry("Mauritius", "+230")
	w.addCountry("Mayotte", "+262")
	w.addCountry("Mexico", "+52")
	w.addCountry("Micronesia, Federated States of", "+691")
	w.addCountry("Midway Island, USA", "+1")
	w.addCountry("Moldova", "+373")
	w.addCountry("Monaco", "+377")
	w.addCountry("Mongolia", "+976")
	w.addCountry("Montenegro", "+382")
	w.addCountry("Montserrat", "+1")
	w.addCountry("Morocco", "+212")
	w.addCountry("Mozambique", "+258")
	w.addCountry("Myanmar", "+95")
	w.addCountry("Nagorno-Karabakh", "+374")
	w.addCountry("Namibia", "+264")
	w.addCountry("Nauru", "+674")
	w.addCountry("Nepal", "+977")
	w.addCountry("Netherlands", "+31")
	w.addCountry("Nevis", "+1")
	w.addCountry("New Caledonia", "+687")
	w.addCountry("New Zealand", "+64")
	w.addCountry("Nicaragua", "+505")
	w.addCountry("Niger", "+227")
	w.addCountry("Nigeria", "+234")
	w.addCountry("Niue", "+683")
	w.addCountry("Norfolk Island", "+672")
	w.addCountry("North Macedonia", "+389")
	w.addCountry("Northern Cyprus", "+90")
	w.addCountry("Northern Ireland", "+44")
	w.addCountry("Northern Mariana Islands", "+1")
	w.addCountry("Norway", "+47")
	w.addCountry("Oman", "+968")
	w.addCountry("Pakistan", "+92")
	w.addCountry("Palau", "+680")
	w.addCountry("Palestine", "+970")
	w.addCountry("Panama", "+507")
	w.addCountry("Papua New Guinea", "+675")
	w.addCountry("Paraguay", "+595")
	w.addCountry("Peru", "+51")
	w.addCountry("Philippines", "+63")
	w.addCountry("Pitcairn Islands", "+64")
	w.addCountry("Poland", "+48")
	w.addCountry("Portugal", "+351")
	w.addCountry("Puerto Rico", "+1")
	w.addCountry("Qatar", "+974")
	w.addCountry("Réunion", "+262")
	w.addCountry("Romania", "+40")
	w.addCountry("Russia", "+7")
	w.addCountry("Rwanda", "+250")
	w.addCountry("Saba", "+599")
	w.addCountry("Saint Barthélemy", "+590")
	w.addCountry("Saint Helena", "+290")
	w.addCountry("Saint Kitts and Nevis", "+1")
	w.addCountry("Saint Lucia", "+1")
	w.addCountry("Saint Martin (France)", "+590")
	w.addCountry("Saint Pierre and Miquelon", "+508")
	w.addCountry("Saint Vincent and the Grenadines", "+1")
	w.addCountry("Samoa", "+685")
	w.addCountry("San Marino", "+378")
	w.addCountry("São Tomé and Príncipe", "+239")
	w.addCountry("Saudi Arabia", "+966")
	w.addCountry("Senegal", "+221")
	w.addCountry("Serbia", "+381")
	w.addCountry("Seychelles", "+248")
	w.addCountry("Sierra Leone", "+232")
	w.addCountry("Singapore", "+65")
	w.addCountry("Sint Eustatius", "+599")
	w.addCountry("Sint Maarten (Netherlands)", "+1")
	w.addCountry("Slovakia", "+421")
	w.addCountry("Slovenia", "+386")
	w.addCountry("Solomon Islands", "+677")
	w.addCountry("Somalia", "+252")
	w.addCountry("South Africa", "+27")
	w.addCountry("South Georgia and the South Sandwich Islands", "+500")
	w.addCountry("South Ossetia", "+995")
	w.addCountry("South Sudan", "+211")
	w.addCountry("Spain", "+34")
	w.addCountry("Sri Lanka", "+94")
	w.addCountry("Sudan", "+249")
	w.addCountry("Suriname", "+597")
	w.addCountry("Svalbard", "+47")
	w.addCountry("Sweden", "+46")
	w.addCountry("Switzerland", "+41")
	w.addCountry("Syria", "+963")
	w.addCountry("Taiwan", "+886")
	w.addCountry("Tajikistan", "+992")
	w.addCountry("Tanzania", "+255")
	w.addCountry("Telecommunications for Disaster Relief by OCHA", "+888")
	w.addCountry("Thailand", "+66")
	w.addCountry("Thuraya (Mobile Satellite service)", "+882")
	w.addCountry("East Timor", "+670")
	w.addCountry("Togo", "+228")
	w.addCountry("Tokelau", "+690")
	w.addCountry("Tonga", "+676")
	w.addCountry("Transnistria", "+373")
	w.addCountry("Trinidad and Tobago", "+1")
	w.addCountry("Tristan da Cunha", "+290")
	w.addCountry("Tunisia", "+216")
	w.addCountry("Turkey", "+90")
	w.addCountry("Turkmenistan", "+993")
	w.addCountry("Turks and Caicos Islands", "+1")
	w.addCountry("Tuvalu", "+688")
	w.addCountry("Uganda", "+256")
	w.addCountry("Ukraine", "+380")
	w.addCountry("United Arab Emirates", "+971")
	w.addCountry("United Kingdom", "+44")
	w.addCountry("United States", "+1")
	w.addCountry("Universal Personal Telecommunications (UPT)", "+878")
	w.addCountry("Uruguay", "+598")
	w.addCountry("US Virgin Islands", "+1")
	w.addCountry("Uzbekistan", "+998")
	w.addCountry("Vanuatu", "+678")
	w.addCountry("Vatican City State (Holy See)", "+39")
	w.addCountry("Venezuela", "+58")
	w.addCountry("Vietnam", "+84")
	w.addCountry("Wake Island, USA", "+1")
	w.addCountry("Wallis and Futuna", "+681")
	w.addCountry("Yemen", "+967")
	w.addCountry("Zambia", "+260")
	w.addCountry("Zanzibar", "+255")
	w.addCountry("Zimbabwe", "+263")
}
